# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.26)
{
  # A helpful description of your flake
  description = "A naive dotfile manager.";

  # Flake inputs
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  };
  # Flake outputs that other flakes can use
  outputs = { self, nixpkgs }:
    let
      # Nixpkgs overlays
      # Helpers for producing system-specific outputs
      supportedSystems = [ "aarch64-darwin" "x86-64-linux"];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
      pkgsFor = nixpkgs.legacyPackages;
    in {
      packages = forAllSystems (system: {
                default = pkgsFor.${system}.callPackage ./default.nix {  };
        });
      devShells = forAllSystems (system :{
                default = pkgsFor.${system}.callPackage ./shell.nix {  };
        });
    };
}
